Support Laravel 8.
SynergiTech/chrome-pdf-php pull request #7
Opened 2021-03-26 16:52 UTC by CraicOverflow89

Updated dependencies and GitHub tests.

2021-03-26 16:55 UTC, willpower232 requested changes
please can you remove the travis file and badge and add trailing newlines to the workflow file and the Dockerfile

2021-03-26 17:00 UTC, willpower232 approved these changes

2021-03-29 08:28 UTC, Josh-G requested changes

2021-03-29 08:28 UTC, Josh-G commented on src/Chrome.php
> +        return new $this->{'processClass'}([$cmdline]);
there's a docblock issue here, `createProcess` is doc'd as receiving a string, but actually [receives an array](https://github.com/SynergiTech/chrome-pdf-php/blob/2dc7b9f7a914f8c9d6307eba5bbc54f738e6c2bf/src/Chrome.php#L212)
as such, we don't need to wrap it

2021-04-06 14:31 UTC, Josh-G requested changes

2021-04-06 14:31 UTC, Josh-G commented on .github/workflows/main.yml
> +        laravel: [5, 6, 7, 8]
please drop references to `laravel`, as this library has no hard dependency on it
might be worth replacing with a version matrix on PHP and `symfony/process`

2021-04-06 14:31 UTC, Josh-G commented on Dockerfile
> +RUN vendor/bin/phpunit --configuration phpunit.xml
please can you change this to `RUN composer test`, which should run `phpunit` + `phpstan`

2021-04-06 14:31 UTC, Josh-G commented on README.md
> -[![Build Status](https://travis-ci.org/SynergiTech/chrome-pdf-php.svg?branch=master)](https://travis-ci.org/SynergiTech/chrome-pdf-php)
new status badge:
[![Tests](https://github.com/SynergiTech/chrome-pdf-php/actions/workflows/main.yml/badge.svg)](https://github.com/SynergiTech/chrome-pdf-php/actions/workflows/main.yml)
```
[![Tests](https://github.com/SynergiTech/chrome-pdf-php/actions/workflows/main.yml/badge.svg)](https://github.com/SynergiTech/chrome-pdf-php/actions/workflows/main.yml)
```

2021-04-06 14:31 UTC, Josh-G commented on phpstan.neon
> +        - '#Method App\\Exceptions\\Handler::render\(\) should return Illuminate\\Http\\Response but returns Symfony\\Component\\HttpFoundation\\Response\.#'
Doesn't look like these are real errors in this library? Can you remove these?

2021-04-06 14:31 UTC, Josh-G commented on phpstan.neon
> +    level: 5
Can you bump it up to 8?

2021-04-06 14:31 UTC, Josh-G commented on phpstan.neon
> +        - app
this should be `src`?

2021-04-07 08:40 UTC, CraicOverflow89 commented
Is this okay @Josh-G?

2021-05-05 10:21 UTC, Josh-G approved these changes

2021-05-05 10:29 UTC, merged